hide-cursor-when-typing = true
use-fork = false
confirm-before-quit = false
line-height = 1.125
ignore-selection-foreground-color = true
padding-y = [10, -10]

[bell]
visual = true

[colors]
background = '#030B16'
foreground = '#7DF9AA'
cursor = '#F08D49'
vi-cursor = '#F08D49'
tabs = '#051120'
tabs-active = '#7DF9AA'
tabs-foreground = '#7DF9AA'
tabs-active-foreground = '#030B16'
tabs-active-highlight = '#F08D49'
bar = '#051120'
split = '#051120'
black = '#051120'
blue = '#2196F3'
cyan = '#4FC3F7'
green = '#4CAF50'
magenta = '#AB47BC'
red = '#EF5350'
white = '#7DF9AA'
yellow = '#FFEB3B'
selection-background = '#F08D49'
selection-foreground = '#030B16'
search-match-background = '#F08D49'
search-match-foreground = '#030B16'
search-focused-match-background = '#FFEB3B'
search-focused-match-foreground = '#030B16'
hint-foreground = '#030B16'
hint-background = '#F08D49'
dim-black = '#051120'
dim-blue = '#1565C0'
dim-cyan = '#0277BD'
dim-green = '#2E7D32'
dim-magenta = '#6A1B9A'
dim-red = '#C62828'
dim-white = '#4DB6AC'
dim-yellow = '#FBC02D'
light-black = '#7DF9AA'
light-blue = '#42A5F5'
light-cyan = '#4DD0E1'
light-green = '#66BB6A'
light-magenta = '#BA68C8'
light-red = '#EF5350'
light-white = '#E0F2F1'
light-yellow = '#FFF176'

[cursor]
shape = 'block'

[editor]
program = "vi"
args = []

[fonts]
family = "Monaspace Neon NF"
size = 16
use-drawable-chars = true
features = [
  "calt=1",
  "liga=1",
  "ss01=1",
  "ss02=1",
  "ss03=1",
  "ss04=1",
  "ss05=1",
  "ss06=1",
  "ss07=1",
  "ss08=1",
  "ss09=1",
  "ss10=1",
]

[fonts.regular]
family = "Monaspace Neon NF"
style = "Normal"
weight = 400

[fonts.bold]
family = "Monaspace Neon NF"
style = "Normal"
weight = 700

[fonts.italic]
family = "Monaspace Neon NF"
style = "Italic"
weight = 400

[fonts.bold-italic]
family = "Monaspace Neon NF"
style = "Italic"
weight = 700

[keyboard]
use-kitty-keyboard-protocol = true
disable-ctlseqs-alt = false
ime-cursor-positioning = true

[navigation]
mode = "TopTab"
clickable = true
hide-if-single = true

[renderer]
performance = "high"
backend = "Vulkan"
disable-unfocused-render = true
disable-occluded-render = true
target-fps = 120
level = 1

[scroll]
multiplier = 3.0
divider = 1.0

[shell]
program = "C:\\Windows\\System32\\wsl.exe"
args = ["-d", "Ubuntu-24.04", "--cd", "~"]

[title]
placeholder = "â–² Rio"

[window]
width = 1920
height = 1080
mode = "maximized"
opacity = 1.0
blur = false
decorations = "Enabled"
windows-corner-preference = "Round"
windows-use-undecorated-shadow = false
working-dir = "~"
