# Previous color scheme: fg:#7df9aa bg:#030b16
"$schema" = 'https://starship.rs/config-schema.json' # Get editor completions based on the config schema

format = """\
$directory\
$git_branch\
$git_status $git_metrics\ 
$fill\
$cmd_duration\
$time\
$jobs\
$line_break$character\
"""

[directory]
format = "[$path ]($style)"
style = "fg:#7DF9AA"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

# [directory.substitutions]
# "Documents" = "󰈙"
# "Downloads" = " "
# "Music" = " "
# "Pictures" = " "
# "~/projects/" = "projects/"
# "~/.config/" = "config/"
# "~/.config/nvim" = "nvim/"

[git_status]
format = "[($staged$modified$untracked$deleted$stashed$conflicted$ahead_behind)]($style)"
staged = "[+$count](yellow) "
modified = "[!$count](yellow) "
deleted = "[-$count](red) "

untracked = "[?$count](green) "
stashed = "[*$count](magenta) "

conflicted = "[!$count](bold red) "
ahead = " [⇡${count}](bold magenta)"
behind = " [⇣${count}](bold magenta)"
diverged = " [⇡${ahead_count}⇣${behind_count}](bold magenta)"

[git_branch]
symbol = " "
format = '[ $symbol$branch(:$remote_branch) ]($style)'
style = "fg:#7DF9AA"

# [git_status]
# format = '[$all_status$ahead_behind]($style)'
# style = "fg:#7DF9AA"

[git_metrics]
disabled = false
format = "([+$added]($added_style) [-$deleted]($deleted_style))"

[time]
disabled = false
time_format = "%I:%M %p"
format = '[  $time ]($style)'
style = "fg:#7DF9AA"

[cmd_duration]
min_time = 0
format = '[  $duration ]($style)'
style = "fg:#7DF9AA"

[character]
success_symbol = '[ ➜](bold green) '
error_symbol = '[ ✗](#E84D44) '

[fill]
symbol = " "
