[tools]
java = "latest"
lazydocker = "latest"
uv = "latest"
bun = "latest"
python = "latest"
gradle = "latest"
deno = "latest"
lazygit = "latest"
maven = "latest"
neovim = "latest"
node = "latest"
starship = "latest"
bat = "latest"
biome = "latest"
eza = "latest"
oxlint = "latest"
go = "latest"
rust = "stable"
fzf = "latest"
rg = "latest"
ripgrep-all = "latest"
delta = "latest"
rye = "latest"
ruff = "latest"
tlrc = "latest"
scooter = "latest"
qsv = "latest"
yazi = "latest"
television = "latest"
tokei = "latest"
k9s = "latest"
kubectl = "latest"
kind = "latest"
glow = "latest"
atuin = "latest"
mongodb = "latest"
mongosh = "latest"
jq = "latest"
gemini-cli = "latest"
hyperfine = "latest"
bottom = "latest"
zig = "latest"
xh = "latest"
zellij = "latest"
docker-compose = "latest"
lua = "latest"
lychee = "latest"
rmz = "latest"
opencode = "latest"
pnpm = "latest"
minikube = "latest"
gitleaks = "latest"

[settings]
lockfile = true
python.uv_venv_auto = true
